# Generated by Django 5.2.4 on 2026-04-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название проекта')),
                ('description', models.TextField(blank=True, verbose_name='описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('github_url', models.URLField(blank=True, verbose_name='ссылка на GitHub')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
